dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
        - cmake
        - libgoogle-glog-dev
        - libc++-dev

env:
  - SCRATCHQL_ROOT=$PWD

git:
  depth: 3

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/gcc-9.0 && sudo apt-get -q update && sudo apt-get -y install gcc-9
#  - gcc-9 -v && sudo rm /usr/bin/gcc && sudo mv /usr/bin/gcc-9 /usr/bin/gcc && gcc -v
#  - g++-9 -v && sudo rm /usr/bin/g++ && sudo mv /usr/bin/g++-9 /usr/bin/g++ && g++ -v
  - sudo find /usr -name "g++*"
  - g++-9 --version
  - curl -O https://capnproto.org/capnproto-c++-0.8.0.tar.gz && tar zxf capnproto-c++-0.8.0.tar.gz && cd capnproto-c++-0.8.0 && ./configure && make -j6 check && sudo make install && cd ../
  - wd="$PWD" && cd .. && git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd $wd

script:
  - cmake -H. -Bbuild
  - cmake --build build --target Test && mkdir tmp && ./build/Test
  - cmake --build build --target Database
