dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
        - cmake
        - libgoogle-glog-dev

env:
  - SCRATCHQL_ROOT=$PWD

git:
  depth: 3

before_install:
  - wd="$PWD" && cd .. && git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd $wd

script:
  - cmake -H. -Bbuild
  - cmake --build build --target Test && mkdir tmp && ./build/Test
  - cmake --build build --target Database
